# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2022-05-05 07:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitorname', models.CharField(max_length=50)),
                ('visitoremail', models.EmailField(max_length=254)),
                ('visitorage', models.IntegerField(validators=[django.core.validators.MaxValueValidator(80), django.core.validators.MinValueValidator(18)])),
            ],
        ),
    ]
